/*
 *   THIS IS A MECHANICALLY GENERATED FILE - DO NOT EDIT
 *   See the makefile (tads/html/win32/makefile.vc5) for information on how
 *   this file is generated and used.
 */

W32KEYBINDING("Global", "Ctrl+A", ID_SCI_SELECTALL, "Ctrl+A = Edit.SelectAll") /* Edit.SelectAll */
W32KEYBINDING("Global", "Ctrl+Insert", ID_SCI_COPY, "Ctrl+Insert = Edit.Copy") /* Edit.Copy */
W32KEYBINDING("Global", "Ctrl+C", ID_SCI_COPY, "Ctrl+C = Edit.Copy") /* Edit.Copy */
W32KEYBINDING("Global", "Ctrl+E", ID_DEBUG_EVALUATE, "Ctrl+E = Debug.Evaluate") /* Debug.Evaluate */
W32KEYBINDING("Global", "Ctrl+F", ID_EDIT_FIND, "Ctrl+F = Edit.Find") /* Edit.Find */
W32KEYBINDING("Global", "Ctrl+R", ID_EDIT_REPLACE, "Ctrl+R = Edit.Replace") /* Edit.Replace */
W32KEYBINDING("Global", "Ctrl+Shift+F", ID_PROJ_SEARCH, "Ctrl+Shift+F = Project.SearchFiles") /* Project.SearchFiles */
W32KEYBINDING("Global", "Ctrl+L", ID_EDIT_GOTOLINE, "Ctrl+L = Edit.GoToLine") /* Edit.GoToLine */
W32KEYBINDING("Global", "Shift+Delete", ID_SCI_CUT, "Shift+Delete = Edit.Cut") /* Edit.Cut */
W32KEYBINDING("Global", "Ctrl+X", ID_SCI_CUT, "Ctrl+X = Edit.Cut") /* Edit.Cut */
W32KEYBINDING("Global", "Shift+Insert", ID_SCI_PASTE, "Shift+Insert = Edit.Paste") /* Edit.Paste */
W32KEYBINDING("Global", "Ctrl+V", ID_SCI_PASTE, "Ctrl+V = Edit.Paste") /* Edit.Paste */
W32KEYBINDING("Global", "Alt+Backspace", ID_SCI_UNDO, "Alt+Backspace = Edit.Undo") /* Edit.Undo */
W32KEYBINDING("Global", "Ctrl+Z", ID_SCI_UNDO, "Ctrl+Z = Edit.Undo") /* Edit.Undo */
W32KEYBINDING("Global", "Ctrl+Y", ID_SCI_REDO, "Ctrl+Y = Edit.Redo") /* Edit.Redo */
W32KEYBINDING("Global", "Ctrl+O", ID_FILE_OPEN, "Ctrl+O = File.Open") /* File.Open */
W32KEYBINDING("Global", "Ctrl+P", ID_FILE_PRINT, "Ctrl+P = File.Print") /* File.Print */
W32KEYBINDING("Global", "Ctrl+Shift+O", ID_FILE_LOADGAME, "Ctrl+Shift+O = File.OpenProject") /* File.OpenProject */
W32KEYBINDING("Global", "Ctrl+S", ID_FILE_SAVE, "Ctrl+S = File.Save") /* File.Save */
W32KEYBINDING("Global", "Ctrl+Shift+S", ID_FILE_SAVE_ALL, "Ctrl+Shift+S = File.SaveAll") /* File.SaveAll */
W32KEYBINDING("Global", "Ctrl+W", ID_FILE_CLOSE, "Ctrl+W = File.Close") /* File.Close */
W32KEYBINDING("Global", "F12", ID_FILE_SAVE_AS, "F12 = File.SaveAs") /* File.SaveAs */
W32KEYBINDING("Global", "Ctrl+N", ID_FILE_NEW, "Ctrl+N = File.New") /* File.New */
W32KEYBINDING("Global", "Ctrl+Shift+N", ID_FILE_CREATEGAME, "Ctrl+Shift+N = File.NewProject") /* File.NewProject */
W32KEYBINDING("Global", "Ctrl+T", ID_FILE_EDIT_TEXT, "Ctrl+T = File.SendToExternalEditor") /* File.SendToExternalEditor */
W32KEYBINDING("Global", "Alt+Num*", ID_DEBUG_SHOWNEXTSTATEMENT, "Alt+Num* = Debug.ShowNextStatement") /* Debug.ShowNextStatement */
W32KEYBINDING("Global", "F1", ID_HELP_TOPICS, "F1 = Help.Topics") /* Help.Topics */
W32KEYBINDING("Global", "Ctrl+G", ID_EDIT_FINDNEXT, "Ctrl+G = Edit.FindNext") /* Edit.FindNext */
W32KEYBINDING("Global", "F3", ID_EDIT_FINDNEXT, "F3 = Edit.FindNext") /* Edit.FindNext */
W32KEYBINDING("Global", "F4", ID_DEBUG_RUNTOCURSOR, "F4 = Debug.RunToCursor") /* Debug.RunToCursor */
W32KEYBINDING("Global", "F5", ID_DEBUG_GO, "F5 = Debug.Go") /* Debug.Go */
W32KEYBINDING("Global", "Ctrl+F5", ID_BUILD_COMP_AND_RUN, "Ctrl+F5 = Build.CompileAndRun") /* Build.CompileAndRun */
W32KEYBINDING("Global", "F7", ID_BUILD_COMPDBG, "F7 = Build.CompileForDebug") /* Build.CompileForDebug */
W32KEYBINDING("Global", "Alt+F7", ID_BUILD_SETTINGS, "Alt+F7 = Build.Settings") /* Build.Settings */
W32KEYBINDING("Global", "F9", ID_DEBUG_SETCLEARBREAKPOINT, "F9 = Debug.SetClearBreakpoint") /* Debug.SetClearBreakpoint */
W32KEYBINDING("Global", "Alt+F9", ID_DEBUG_EDITBREAKPOINTS, "Alt+F9 = Debug.EditBreakpoints") /* Debug.EditBreakpoints */
W32KEYBINDING("Global", "Ctrl+F9", ID_DEBUG_DISABLEBREAKPOINT, "Ctrl+F9 = Debug.DisableBreakpoint") /* Debug.DisableBreakpoint */
W32KEYBINDING("Global", "F10", ID_DEBUG_STEPOVER, "F10 = Debug.StepOver") /* Debug.StepOver */
W32KEYBINDING("Global", "F11", ID_DEBUG_STEPINTO, "F11 = Debug.StepInto") /* Debug.StepInto */
W32KEYBINDING("Global", "Shift+F11", ID_DEBUG_STEPOUT, "Shift+F11 = Debug.StepOut") /* Debug.StepOut */
W32KEYBINDING("Global", "Alt+J", ID_EDIT_POPBOOKMARK, "Alt+J = Edit.PopBookmark") /* Edit.PopBookmark */
W32KEYBINDING("Global", "Ctrl+Shift+J", ID_EDIT_JUMPNEXTBOOKMARK, "Ctrl+Shift+J = Edit.JumpToNextBookmark") /* Edit.JumpToNextBookmark */
W32KEYBINDING("Global", "Ctrl+J", ID_EDIT_JUMPNAMEDBOOKMARK, "Ctrl+J = Edit.JumpToNamedBookmark") /* Edit.JumpToNamedBookmark */
W32KEYBINDING("Text Editor", "Ctrl+F3", ID_EDIT_INCSEARCH, "Ctrl+F3 = Edit.SearchIncremental") /* Edit.SearchIncremental */
W32KEYBINDING("Text Editor", "Down", ID_SCI_LINEDOWN, "Down = Edit.LineDown") /* Edit.LineDown */
W32KEYBINDING("Text Editor", "Ctrl+Down", ID_SCI_LINESCROLLDOWN, "Ctrl+Down = Edit.LineScrollDown") /* Edit.LineScrollDown */
W32KEYBINDING("Text Editor", "Shift+Down", ID_SCI_LINEDOWNEXTEND, "Shift+Down = Edit.LineDownExtend") /* Edit.LineDownExtend */
W32KEYBINDING("Text Editor", "Shift+Alt+Down", ID_SCI_LINEDOWNRECTEXTEND, "Shift+Alt+Down = Edit.LineDownRectExtend") /* Edit.LineDownRectExtend */
W32KEYBINDING("Text Editor", "Up", ID_SCI_LINEUP, "Up = Edit.LineUp") /* Edit.LineUp */
W32KEYBINDING("Text Editor", "Ctrl+Up", ID_SCI_LINESCROLLUP, "Ctrl+Up = Edit.LineScrollUp") /* Edit.LineScrollUp */
W32KEYBINDING("Text Editor", "Shift+Up", ID_SCI_LINEUPEXTEND, "Shift+Up = Edit.LineUpExtend") /* Edit.LineUpExtend */
W32KEYBINDING("Text Editor", "Shift+Alt+Up", ID_SCI_LINEUPRECTEXTEND, "Shift+Alt+Up = Edit.LineUpRectExtend") /* Edit.LineUpRectExtend */
W32KEYBINDING("Text Editor", "Left", ID_SCI_CHARLEFT, "Left = Edit.CharLeft") /* Edit.CharLeft */
W32KEYBINDING("Text Editor", "Shift+Left", ID_SCI_CHARLEFTEXTEND, "Shift+Left = Edit.CharLeftExtend") /* Edit.CharLeftExtend */
W32KEYBINDING("Text Editor", "Ctrl+Left", ID_SCI_WORDLEFT, "Ctrl+Left = Edit.WordLeft") /* Edit.WordLeft */
W32KEYBINDING("Text Editor", "Ctrl+Shift+Left", ID_SCI_WORDLEFTEXTEND, "Ctrl+Shift+Left = Edit.WordLeftExtend") /* Edit.WordLeftExtend */
W32KEYBINDING("Text Editor", "Shift+Alt+Left", ID_SCI_CHARLEFTRECTEXTEND, "Shift+Alt+Left = Edit.CharLeftRectExtend") /* Edit.CharLeftRectExtend */
W32KEYBINDING("Text Editor", "Right", ID_SCI_CHARRIGHT, "Right = Edit.CharRight") /* Edit.CharRight */
W32KEYBINDING("Text Editor", "Shift+Right", ID_SCI_CHARRIGHTEXTEND, "Shift+Right = Edit.CharRightExtend") /* Edit.CharRightExtend */
W32KEYBINDING("Text Editor", "Ctrl+Right", ID_SCI_WORDRIGHT, "Ctrl+Right = Edit.WordRight") /* Edit.WordRight */
W32KEYBINDING("Text Editor", "Ctrl+Shift+Right", ID_SCI_WORDRIGHTEXTEND, "Ctrl+Shift+Right = Edit.WordRightExtend") /* Edit.WordRightExtend */
W32KEYBINDING("Text Editor", "Shift+Alt+Right", ID_SCI_CHARRIGHTRECTEXTEND, "Shift+Alt+Right = Edit.CharRightRectExtend") /* Edit.CharRightRectExtend */
W32KEYBINDING("Text Editor", "Home", ID_SCI_HOME, "Home = Edit.Home") /* Edit.Home */
W32KEYBINDING("Text Editor", "Ctrl+Home", ID_SCI_DOCUMENTSTART, "Ctrl+Home = Edit.DocumentStart") /* Edit.DocumentStart */
W32KEYBINDING("Text Editor", "Shift+Home", ID_SCI_HOMEEXTEND, "Shift+Home = Edit.HomeExtend") /* Edit.HomeExtend */
W32KEYBINDING("Text Editor", "Shift+Alt+Home", ID_SCI_VCHOMERECTEXTEND, "Shift+Alt+Home = Edit.IndentHomeRectExtend") /* Edit.IndentHomeRectExtend */
W32KEYBINDING("Text Editor", "Ctrl+Shift+Home", ID_SCI_DOCUMENTSTARTEXTEND, "Ctrl+Shift+Home = Edit.DocumentStartExtend") /* Edit.DocumentStartExtend */
W32KEYBINDING("Text Editor", "Alt+Home", ID_SCI_HOMEDISPLAY, "Alt+Home = Edit.HomeDisplay") /* Edit.HomeDisplay */
W32KEYBINDING("Text Editor", "End", ID_SCI_LINEEND, "End = Edit.LineEnd") /* Edit.LineEnd */
W32KEYBINDING("Text Editor", "Shift+End", ID_SCI_LINEENDEXTEND, "Shift+End = Edit.LineEndExtend") /* Edit.LineEndExtend */
W32KEYBINDING("Text Editor", "Ctrl+End", ID_SCI_DOCUMENTEND, "Ctrl+End = Edit.DocumentEnd") /* Edit.DocumentEnd */
W32KEYBINDING("Text Editor", "Ctrl+Shift+End", ID_SCI_DOCUMENTENDEXTEND, "Ctrl+Shift+End = Edit.DocumentEndExtend") /* Edit.DocumentEndExtend */
W32KEYBINDING("Text Editor", "Alt+End", ID_SCI_LINEENDDISPLAY, "Alt+End = Edit.LineEndDisplay") /* Edit.LineEndDisplay */
W32KEYBINDING("Text Editor", "Shift+Alt+End", ID_SCI_LINEENDRECTEXTEND, "Shift+Alt+End = Edit.LineEndRectExtend") /* Edit.LineEndRectExtend */
W32KEYBINDING("Text Editor", "PageUp", ID_SCI_STUTTEREDPAGEUP, "PageUp = Edit.StutteredPageUp") /* Edit.StutteredPageUp */
W32KEYBINDING("Text Editor", "Shift+PageUp", ID_SCI_STUTTEREDPAGEUPEXTEND, "Shift+PageUp = Edit.StutteredPageUpExtend") /* Edit.StutteredPageUpExtend */
W32KEYBINDING("Text Editor", "Shift+Alt+PageUp", ID_SCI_PAGEUPRECTEXTEND, "Shift+Alt+PageUp = Edit.PageUpRectExtend") /* Edit.PageUpRectExtend */
W32KEYBINDING("Text Editor", "PageDown", ID_SCI_STUTTEREDPAGEDOWN, "PageDown = Edit.StutteredPageDown") /* Edit.StutteredPageDown */
W32KEYBINDING("Text Editor", "Shift+PageDown", ID_SCI_STUTTEREDPAGEDOWNEXTEND, "Shift+PageDown = Edit.StutteredPageDownExtend") /* Edit.StutteredPageDownExtend */
W32KEYBINDING("Text Editor", "Shift+Alt+PageDown", ID_SCI_PAGEDOWNRECTEXTEND, "Shift+Alt+PageDown = Edit.PageDownRectExtend") /* Edit.PageDownRectExtend */
W32KEYBINDING("Text Editor", "Delete", ID_EDIT_DELETECHAR, "Delete = Edit.DeleteChar") /* Edit.DeleteChar */
W32KEYBINDING("Text Editor", "Ctrl+Delete", ID_SCI_DELWORDRIGHT, "Ctrl+Delete = Edit.DelWordRight") /* Edit.DelWordRight */
W32KEYBINDING("Text Editor", "Ctrl+Shift+Delete", ID_SCI_DELLINERIGHT, "Ctrl+Shift+Delete = Edit.DelLineRight") /* Edit.DelLineRight */
W32KEYBINDING("Text Editor", "Insert", ID_SCI_EDITTOGGLEOVERTYPE, "Insert = Edit.ToggleOvertype") /* Edit.ToggleOvertype */
W32KEYBINDING("Text Editor", "Backspace", ID_SCI_DELETEBACK, "Backspace = Edit.DeleteBack") /* Edit.DeleteBack */
W32KEYBINDING("Text Editor", "Shift+Backspace", ID_SCI_DELETEBACK, "Shift+Backspace = Edit.DeleteBack") /* Edit.DeleteBack */
W32KEYBINDING("Text Editor", "Ctrl+Backspace", ID_SCI_DELWORDLEFT, "Ctrl+Backspace = Edit.DelWordLeft") /* Edit.DelWordLeft */
W32KEYBINDING("Text Editor", "Ctrl+Shift+Backspace", ID_SCI_DELLINELEFT, "Ctrl+Shift+Backspace = Edit.DelLineLeft") /* Edit.DelLineLeft */
W32KEYBINDING("Text Editor", "Shift+Delete", ID_SCI_CUT, "Shift+Delete = Edit.Cut") /* Edit.Cut */
W32KEYBINDING("Text Editor", "Tab", ID_SCI_TAB, "Tab = Edit.Tab") /* Edit.Tab */
W32KEYBINDING("Text Editor", "Shift+Tab", ID_SCI_BACKTAB, "Shift+Tab = Edit.BackTab") /* Edit.BackTab */
W32KEYBINDING("Text Editor", "Enter", ID_SCI_NEWLINE, "Enter = Edit.Newline") /* Edit.Newline */
W32KEYBINDING("Text Editor", "Shift+Enter", ID_SCI_NEWLINE, "Shift+Enter = Edit.Newline") /* Edit.Newline */
W32KEYBINDING("Text Editor", "Esc", ID_SCI_CANCEL, "Esc = Edit.Cancel") /* Edit.Cancel */
W32KEYBINDING("Text Editor", "Ctrl+I", (null), "Ctrl+I = Ext.Edit.SyntaxIndent") /* Ext.Edit.SyntaxIndent */
W32KEYBINDING("Text Editor", "Ctrl+U", ID_EDIT_REPEATCOUNT, "Ctrl+U = Edit.RepeatCount") /* Edit.RepeatCount */
W32KEYBINDING("Text Editor", "Ctrl+Q", ID_EDIT_QUOTEKEY, "Ctrl+Q = Edit.QuoteKey") /* Edit.QuoteKey */
W32KEYBINDING("Text Editor", "Alt+Q", ID_EDIT_FILL_PARA, "Alt+Q = Edit.FillParagraph") /* Edit.FillParagraph */
W32KEYBINDING("Text Editor", "Alt+X", ID_EDIT_SWAP_MARK, "Alt+X = Edit.SwapMark") /* Edit.SwapMark */
W32KEYBINDING("Text Editor", "Shift+Alt+X", ID_EDIT_SELECT_TO_MARK, "Shift+Alt+X = Edit.SelectToMark") /* Edit.SelectToMark */
W32KEYBINDING("Text Editor", "Alt+/", ID_EDIT_TOGGLEBOOKMARK, "Alt+/ = Edit.ToggleBookmark") /* Edit.ToggleBookmark */
W32KEYBINDING("Text Editor", "Alt+?", ID_EDIT_SETNAMEDBOOKMARK, "Alt+? = Edit.SetNamedBookmark") /* Edit.SetNamedBookmark */
W32KEYBINDING("Text Editor", "Ctrl+8", ID_EDIT_ADDCOMMENT, "Ctrl+8 = Edit.CommentRegion") /* Edit.CommentRegion */
W32KEYBINDING("Text Editor", "F6", ID_EDIT_FINDSYMDEF, "F6 = Edit.FindDefinition") /* Edit.FindDefinition */
W32KEYBINDING("Incremental Search", "Ctrl+F", ID_ISEARCH_FINDNEXT, "Ctrl+F = Edit.IncSearch.Next") /* Edit.IncSearch.Next */
W32KEYBINDING("Incremental Search", "Ctrl+F3", ID_ISEARCH_FINDNEXT, "Ctrl+F3 = Edit.IncSearch.Next") /* Edit.IncSearch.Next */
W32KEYBINDING("Incremental Search", "Ctrl+R", ID_ISEARCH_FINDPREV, "Ctrl+R = Edit.IncSearch.Prev") /* Edit.IncSearch.Prev */
W32KEYBINDING("Incremental Search", "Backspace", ID_ISEARCH_BACKSPACE, "Backspace = Edit.IncSearch.Backspace") /* Edit.IncSearch.Backspace */
W32KEYBINDING("Incremental Search", "Ctrl+C", ID_ISEARCH_CASE, "Ctrl+C = Edit.IncSearch.ToggleExactCase") /* Edit.IncSearch.ToggleExactCase */
W32KEYBINDING("Incremental Search", "Ctrl+T", ID_ISEARCH_REGEX, "Ctrl+T = Edit.IncSearch.ToggleRegEx") /* Edit.IncSearch.ToggleRegEx */
W32KEYBINDING("Incremental Search", "Ctrl+W", ID_ISEARCH_WORD, "Ctrl+W = Edit.IncSearch.ToggleWord") /* Edit.IncSearch.ToggleWord */
W32KEYBINDING("Incremental Search", "Ctrl+G", ID_ISEARCH_CANCEL, "Ctrl+G = Edit.IncSearch.Cancel") /* Edit.IncSearch.Cancel */
W32KEYBINDING("Incremental Search", "Esc", ID_ISEARCH_EXIT, "Esc = Edit.IncSearch.Exit") /* Edit.IncSearch.Exit */
